---
title: "AAEA-2024 Agricultural Services"
format:
  html:
    toc: true
    code-fold: true
    df-print: paged
    embed-resources: true
---

# imports

```{r}
#| output: false
library(tidyverse)
library(glue)
library(marginaleffects)
library(huxtable)
library(arrow)

source("scripts/agser_aaea.R")
```


# pubdata

```{r}
agcensus(2022) %>%
  head() %>%
  collect()

qcew(2022) %>%
  head() %>%
  collect()
```

# farms

"AG SERVICES, CUSTOM SERVICES FOR LIVESTOCK, INCL MEDICAL SUPPLIES & VETERINARY - EXPENSE, MEASURED IN $"
only appears in 2017 and 2022. why?

```{r}
# verify Delaware against PDF published tables
data$farm() %>%
  filter(str_sub(stcty, 1, 2) == "10", year == 2022) %>%
  pivot_wider(id_cols = c(year, stcty))

data$farm() %>%
  pivot_wider(id_cols = c(year, stcty)) %>%
  group_by(year) %>%
  summarize(across(is.numeric, \(x) sum(x, na.rm = TRUE)))

```

## hogs sold per stock

```{r}
renames <- tribble(
  ~name, ~short_desc,
  "output_pig", "HOGS - SALES, MEASURED IN HEAD",
  "output_beef", "CATTLE, INCL CALVES - SALES, MEASURED IN HEAD",
  "stock_pig", "HOGS - INVENTORY",
  "stock_beef", "CATTLE, COWS, BEEF - INVENTORY"
)

d <- agcensus() %>%
    filter(agg_level_desc == "COUNTY", domain_desc == "TOTAL", short_desc %in% renames$short_desc) %>%
    mutate(stcty = paste0(state_fips_code, county_code)) %>%
    select(year, st = state_fips_code, stcty, short_desc, value) %>%
    collect() %>%
    left_join(renames, "short_desc") %>%
    pivot_wider(id_cols = c(year, stcty)) %>%
    mutate(
      output_to_stock_pig = output_pig / stock_pig,
      output_to_stock_beef = output_beef / stock_beef
    )

# delaware = 10
# d %>% filter(year == 2017, str_starts(stcty, "10"))


d %>%
  ggplot() +
  geom_boxplot(aes(factor(year), output_to_stock_pig)) +
  scale_y_log10()

d %>%
  ggplot() +
  geom_boxplot(aes(factor(year), output_to_stock_beef)) +
  scale_y_log10()

```


## crop productivity

```{r}

# manually download productivity indexes file
d0 <- readxl::read_excel("~/Downloads/table01.xlsx", skip = 2, n_max = 75)

names(d0)

d0 %>%
  mutate(yield = `Crops output: Total` / `Capital inputs: Land`) %>%
  filter(Year > 2001) %>%
  ggplot() + 
  geom_line(aes(Year, yield)) +
  geom_line(aes(Year, `Crops output: Total`), color = "red") +
  geom_line(aes(Year, `Capital inputs: Land`), color = "blue")

```



## custom work and size

```{r}
df <- data$farm()
d <- df %>%
  pivot_wider(id_cols = c(year, stcty)) %>%
  mutate(avgsale_crop = sale_crop / n_sale_crop, sh_agser_cust = exp_agser_cust / exp_tot)

d %>%
  ggplot(aes(avgsale_crop, sh_agser_cust)) +
  geom_point() +
  geom_smooth() + 
  scale_x_log10() +
  facet_wrap("year")

d %>%
  ggplot(aes(sale_crop, sh_agser_cust)) +
  geom_point() +
  geom_smooth() + 
  scale_x_log10() +
  facet_wrap("year")

d %>%
  group_by(year) %>%
  group_map(\(x, ...) lm(sh_agser_cust ~ log(avgsale_crop), x)) %>%
  map(summary)

```



# agser

```{r}
# in 2002 estabs are not available in suppressed rows
data$agser() %>%
  group_by(year, disc) %>%
  summarize(n = n(), est = sum(est, na.rm = TRUE), .groups = "drop")

```



# models

```{r}
x1 <- data$farm() %>%
  pivot_wider(id_cols = c(year, stcty)) %>%
  select(year, stcty, sale_tot, asset_tot, exp_labhire, exp_labcont, exp_agser) %>%
  mutate(across(c(sale_tot, asset_tot, exp_labhire, exp_labcont, exp_agser), \(x) log10(replace_na(x, 0) + 1)))

x2 <- data$agser() %>%
  mutate(agser_act = (est > 0) | (disc == "N")) %>%
  select(year, stcty, agser_act)
  
df <- left_join(x1, x2, join_by(year, stcty)) %>%
  mutate(agser_act = replace_na(agser_act, FALSE),
         year = as.factor(year))
df %>% summary()

ms <- list()
ms[["base"]] <- lm(sale_tot ~ asset_tot + exp_labhire + exp_labcont + exp_agser + year, data = df)
ms[["tfp"]] <- lm(sale_tot ~ asset_tot + exp_labhire + exp_labcont + exp_agser + agser_act + year, data = df)
ms[["mfp"]] <- lm(sale_tot ~ (asset_tot + exp_labhire + exp_labcont + exp_agser) * agser_act + year, data = df)

huxreg(ms)
```






